### ISSUE TITLE
Weird map rendering in some places

### ISSUE THREAD

**Issue by keneanung** [Delwing/discord-mudlet-map#2]
Some places have weird rendering.

The Achaean map (https://ire-mudlet-mapping.github.io/AchaeaCrowdmap/Map/map), room 12453 renders like this:
![image](https://user-images.githubusercontent.com/1056269/137009722-3511b09d-0584-40ba-8289-80a7911537d6.png)

Room 12452 renders like this:
![image](https://user-images.githubusercontent.com/1056269/137009955-9c4f059a-683a-4e77-a1e5-a21b5acd309e.png)

**Comment by Delwing** [comment]
Fonts missing it is :)
